//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apocryph.Dao.Bot.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apocryph.Dao.Bot.Validators.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrop account is empty.
        /// </summary>
        internal static string AirdropTentUserMessageValidator_AirdropAccountIsEmpty {
            get {
                return ResourceManager.GetString("AirdropTentUserMessageValidator_AirdropAccountIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be a member of TENT discord server.
        /// </summary>
        internal static string AirdropTentUserMessageValidator_UserExistsInTentServer {
            get {
                return ResourceManager.GetString("AirdropTentUserMessageValidator_UserExistsInTentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already participated.
        /// </summary>
        internal static string AirdropTentUserMessageValidator_UserHasParticipatedAlready {
            get {
                return ResourceManager.GetString("AirdropTentUserMessageValidator_UserHasParticipatedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided address is not valid.
        /// </summary>
        internal static string IntroAttemptMessageValidator_Address_NotValid {
            get {
                return ResourceManager.GetString("IntroAttemptMessageValidator_Address_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found.
        /// </summary>
        internal static string IntroAttemptMessageValidator_Session_NotFound {
            get {
                return ResourceManager.GetString("IntroAttemptMessageValidator_Session_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is confirmed already.
        /// </summary>
        internal static string IntroInquiryMessageValidatorr_Address_ConfirmedAlready {
            get {
                return ResourceManager.GetString("IntroInquiryMessageValidatorr_Address_ConfirmedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address already taken.
        /// </summary>
        internal static string IntroInquiryMessageValidatorr_Address_NotAvailable {
            get {
                return ResourceManager.GetString("IntroInquiryMessageValidatorr_Address_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is invalid.
        /// </summary>
        internal static string IntroInquiryMessageValidatorr_Address_NotValid {
            get {
                return ResourceManager.GetString("IntroInquiryMessageValidatorr_Address_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has not been confirmed.
        /// </summary>
        internal static string ValidateUserOnBoarding_UserId_AddressNotConfirmed {
            get {
                return ResourceManager.GetString("ValidateUserOnBoarding_UserId_AddressNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has not been registered.
        /// </summary>
        internal static string ValidateUserOnBoarding_UserId_AddressNotRegistered {
            get {
                return ResourceManager.GetString("ValidateUserOnBoarding_UserId_AddressNotRegistered", resourceCulture);
            }
        }
    }
}
